[package]
name = "my_db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
nix = { version = "0.28.0", features = ["mman", "fs"] }
lazy_static = "1.4.0"